version: '3.6'

networks:
  proxy:
  internal:

services:
  traefik:
    image: 'traefik:alpine'
    container_name: 'traefik'
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:monitor.example.com
      - traefik.port=8080
    networks:
      proxy:
  crud:
    image: 'efossas/crud'
    container_name: 'crud'
    volumes:
      - ./config:/config
    labels:
      - traefik.frontend.rule=Host:localhost
      - traefik.docker.network=proxy
      - traefik.port=443
    networks:
      proxy:
      internal:
    depends_on:
      - mongo
      - redis
  mongo:
    image: 'mongo:xenial'
    container_name: 'mongo'
    labels:
      - traefik.enable=false
      - traefik.docker.network=proxy
    networks:
      proxy:
      internal:
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    labels:
      - traefik.enable=false
      - traefik.docker.network=proxy
    networks:
      proxy:
      internal:
    