# logs
logLevel = "DEBUG"

[traefikLog]

[accessLog]
  [accessLog.filters]
    statusCodes = ["0-600"]

# entry points
[entryPoints]
  [entryPoints.http]
    address = ":80"
  
  [entryPoints.https]
    address = ":443"
  
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/crud.crt"
      keyFile = "/ssl/crud.key"
  
  # traefik web console, password created with: htpasswd -nbB admin default
  [entryPoints.traefik]
   address=":8080"
   [entryPoints.traefik.auth]
     [entryPoints.traefik.auth.basic]
       users = ["admin:$2y$05$5lDlnFzA6TbdzLNd8fY8MOgR3TJwVOZIatEfxvXEj1o6cvvDgfU62"]

# gui
[api]
entrypoint="traefik"

# docker
[docker]
watch = true
exposedbydefault = false
domain = "docker.localhost"